notifications:
  email: false

language: c
sudo: false

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-4.8']
      env: COMPILER=gcc-4.8

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-4.9']
      env: COMPILER=gcc-4.9

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-5']
      env: COMPILER=gcc-5

    - os: linux
      compiler: clang
      env: COMPILER=clang V='3.4'

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.5']
          packages: ['clang-3.5']
      env: COMPILER=clang-3.5

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.6']
          packages: ['clang-3.6']
      env: COMPILER=clang-3.6

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7']
          packages: ['clang-3.7']
      env: COMPILER=clang-3.7

    - os: osx
      compiler: clang
      env: COMPILER=clang V='Apple LLVM 6.0' # Apple LLVM version 6.0 (clang-600.0.54) (based on LLVM 3.5svn)

    - os: osx
      osx_image: xcode7
      compiler: clang
      env: COMPILER=clang V='Apple LLVM 7.0.0' # Apple LLVM version 7.0.0 (clang-700.0.72)

script:
  - make -j4 tests CC=$COMPILER
  - cd xi_theory/python_bindings && python call_correlation_functions.py
  - cd ../../xi_mocks/python_bindings && python call_correlation_functions_mocks.py
