notifications:
  email: false

language: c
sudo: false

matrix:
  fast_finish: true
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-4.8','libgsl0-dev','python-numpy']
      env: COMPILER=gcc-4.8
			before_install:
			  - pip install numpy --user

    # - os: linux
    #   compiler: gcc
    #   addons:
    #     apt:
    #       sources: ['ubuntu-toolchain-r-test']
    #       packages: ['gcc-4.9','libgsl0-dev','python-numpy']
    #   env: COMPILER=gcc-4.9
		# 	before_install:
		# 	  - pip install numpy --user


script:
  - make -j4 distclean && make install CC=$COMPILER && make -j4 tests CC=$COMPILER
  - cd xi_theory/python_bindings && python call_correlation_functions.py
  - cd ../../xi_mocks/python_bindings && python call_correlation_functions_mocks.py
