notifications:
  email: false

language: c
sudo: false

matrix:
  fast_finish: true
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-4.8','libgsl0-dev','python-numpy']
      env: COMPILER=gcc-4.8

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-4.9','libgsl0-dev','python-numpy']
      env: COMPILER=gcc-4.9

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-5','libgsl0-dev','python-numpy']
      env: COMPILER=gcc-5

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['libgsl0-dev','python-numpy']
      env: COMPILER=clang V='3.4'

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.5']
          packages: ['clang-3.5','libgsl0-dev','python-numpy']
      env: COMPILER=clang-3.5

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.6']
          packages: ['clang-3.6','libgsl0-dev','python-numpy']
      env: COMPILER=clang-3.6

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7']
          packages: ['clang-3.7','libgsl0-dev','python-numpy']
      env: COMPILER=clang-3.7

    - os: osx
      compiler: clang
      env: COMPILER=clang V='Apple LLVM 6.0' 

    - os: osx
      osx_image: xcode7
      compiler: clang
      env: COMPILER=clang V='Apple LLVM 7.0.0'

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update && brew install numpy ; fi
			
script:
  - make distclean && make -j4 install CC=$COMPILER && make -j4 tests CC=$COMPILER
  - cd xi_theory/python_bindings && python call_correlation_functions.py
  - cd ../../xi_mocks/python_bindings && python call_correlation_functions_mocks.py
