package:
  name: corrfunc
  version: "2.0.0"

source:
  path: dist
  fn: corrfunc-2.0.0.tar.gz
  md5: 8523662c871c33f3db44ffe535c0e286

  
  # git_url: https://github.com/manodeep/corrfunc.git
  # git_rev: master
  
requirements:
  build:
    - python >=2.6
    - numpy >=1.7
    - setuptools
    - future
    - gsl

  run:
    - python >=2.6
    - future
    - numpy >=1.7
    - gsl

build:
  detect_binary_files_with_prefix: True
  script: python setup.py install --single-version-externally-managed --record record.txt
  binary_relocation: False
  skip: True # [win]
  
test:
  files:
    - theory/tests/data/gals_Mr19.ff
    - mocks/tests/data/Mr19_mock_northonly.rdcz.dat
    - include/countpairs.h
    - include/countpairs_rp_pi_mocks.h
    - theory/tests/bins
    - mocks/tests/bins
    - mocks/tests/angular_bins
    - mocks/tests/data/Mr19_centers_xyz_forVPF_rmax_10Mpc.txt
  imports:
    - corrfunc
    - corrfunc._countpairs
    - corrfunc._countpairs_mocks
    - corrfunc.call_correlation_functions
    - corrfunc.call_correlation_functions_mocks

  commands:
    - python -c "import corrfunc.call_correlation_functions as c; c.main()"
    - python -c "import corrfunc.call_correlation_functions_mocks as m; m.main()"
	
about:
  home: http://manodeep.github.io/corrfunc/
  license: MIT
  license_file: LICENSE
  summary: Blazing fast correlation functions on the CPU
  
extra:
  maintainers:
    - Manodeep Sinha <manodeep@gmail.com>
    
    
